name: "isles24"
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - scikit-learn
  - pandas
  - openpyxl
  - seaborn
  - matplotlib
  - jupyterlab
  - nibabel
  - hatchling
  - pip
  - pip:
    - torch
    - torchvision
    - wandb[importers]
    - lightning
    - monai[all]
    - panoptica
    - -e .
prefix: "/opt/conda"
