name: "isles24"
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyterlab
  - hatchling
  - pip
  - pip:
    - pandas
    - scikit-learn
    - openpyxl
    - matplotlib
    - seaborn
    - nibabel
    - torch
    - torchvision
    - wandb[importers]
    - lightning
    - monai[all]
    - panoptica
    - -e .
prefix: "/opt/conda"
